const DEFAULT_RIGHTS_LABELS={open:'פתוח בתנאים',permission:'נדרש אישור',commercial:'מסחרי',family:'משפחה',production:'הפקה',verify:'טעון בדיקה'};
const MEDIA_LABELS={video:'וידאו',stills:'סטילס',audio:'אודיו',web:'מקור קריאה'};
export const EMBED_HOSTS=new Set(['www.youtube-nocookie.com','www.facebook.com','archive.org']);
export const MEDIA_HOSTS=new Set(['i.ytimg.com','commons.wikimedia.org','upload.wikimedia.org','archive.org','cdn.prod.website-files.com','images.squarespace-cdn.com']);
const LOCAL_PREVIEW_PATH=/\/assets\/previews\/ML-\d{3}\.webp$/;
const DOWNLOAD_HOSTS=new Set(['upload.wikimedia.org']);
const LOCAL_DOWNLOAD_PATH=/^assets\/downloads\/ML-\d{3}\.jpg$/;

let archive=null;
const state={view:'topics',topicId:'',chooserQuery:'',resultQuery:'',pendingItemId:'',lastTopicTrigger:null};
const q=(selector,root=document)=>root.querySelector(selector);
const qa=(selector,root=document)=>[...root.querySelectorAll(selector)];
export const normalize=(value='')=>String(value).normalize('NFKD').replace(/[\u0591-\u05C7]/g,'').toLowerCase().replace(/[״׳'".,:;()\[\]{}\-–—_/\\]/g,' ').replace(/\s+/g,' ').trim();
export function itemSearchText(item){return [item.id,item.title,item.period,item.mediaType,item.description,item.editorialUse,item.subcategory,item.source,item.rightsOwner,item.rightsStatus].filter(Boolean).join(' ')}
export function allTopics(data){return [...(data.meta?.curatedTopics||[]),...(data.meta?.sections||[])]}
export function topicItems(data,topicId,query=''){const curated=(data.meta?.curatedTopics||[]).find(topic=>topic.id===topicId);const allowed=curated?new Set(curated.itemIds):null;const needle=normalize(query);return data.items.filter(item=>(allowed?allowed.has(item.id):item.section===topicId)&&(!needle||normalize([itemSearchText(item),...topicRequestTags(data,topicId,item.id).map(tag=>`${tag.label} ${tag.note||''}`)].join(' ')).includes(needle)))}
export function topicRequestTags(data,topicId,itemId){const topic=(data.meta?.curatedTopics||[]).find(entry=>entry.id===topicId);return (topic?.requestGroups||[]).filter(group=>group.itemIds?.includes(itemId))}
export function parseRoute(hash=''){let match=String(hash).match(/^#topic\/(.+)$/);if(match)return{kind:'topic',id:decodeURIComponent(match[1])};match=String(hash).match(/^#item\/(ML-\d{3})$/);if(match)return{kind:'item',id:match[1]};return{kind:'topics'}}
export function trustedDownloadUrl(item){if(item?.downloadAuthorized!==true||typeof item.downloadUrl!=='string')return'';if(LOCAL_DOWNLOAD_PATH.test(item.downloadUrl))return item.downloadUrl;try{const url=new URL(item.downloadUrl);return url.protocol==='https:'&&DOWNLOAD_HOSTS.has(url.hostname)&&url.pathname.startsWith('/wikipedia/commons/')?url.href:''}catch{return''}}
function safeHttpUrl(value){try{const url=new URL(value,location.href);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return''}}
function trustedEmbedUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&EMBED_HOSTS.has(url.hostname)?url.href:''}catch{return''}}
function trustedMediaUrl(value){try{const url=new URL(value,location.href);if(url.origin===location.origin&&LOCAL_PREVIEW_PATH.test(url.pathname))return url.href;return url.protocol==='https:'&&MEDIA_HOSTS.has(url.hostname)?url.href:''}catch{return''}}
function rightsLabel(item){return archive.meta.rightsLabels?.[item.rightsGroup]||DEFAULT_RIGHTS_LABELS[item.rightsGroup]||item.rightsStatus||'טעון בדיקה'}
function setLink(selector,url){qa(selector).forEach(link=>{const safe=url?safeHttpUrl(url):'';link.hidden=!safe;if(safe)link.href=safe})}
function toast(text){const el=q('[data-toast]');el.textContent=text;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),2200)}
function routeTo(hash,{replace=false}={}){const url=`${location.pathname}${location.search}${hash}`;(replace?history.replaceState:history.pushState).call(history,null,'',url);applyRoute({focus:true})}
function home({restoreFocus=false}={}){state.view='topics';state.topicId='';state.resultQuery='';state.pendingItemId='';q('[data-topic-workspace]').hidden=true;q('[data-chooser]').hidden=false;renderChooser();if(restoreFocus&&state.lastTopicTrigger?.isConnected)state.lastTopicTrigger.focus();else q('#topics-title').focus?.({preventScroll:true})}
function applyRoute({focus=false}={}){if(!archive)return;const route=parseRoute(location.hash);if(route.kind==='topic'&&allTopics(archive).some(section=>section.id===route.id)){showTopic(route.id,{focus});return}if(route.kind==='item'){const item=archive.items.find(entry=>entry.id===route.id);if(item){state.pendingItemId=item.id;showTopic(item.section,{focus,openItem:item.id});return}}if(location.hash)history.replaceState(null,'',`${location.pathname}${location.search}`);home({restoreFocus:focus})}
function mediaSummary(items){const counts={video:0,stills:0,audio:0,web:0};items.forEach(item=>counts[item.mediaGroup]=(counts[item.mediaGroup]||0)+1);return Object.entries(counts).filter(([,count])=>count).map(([kind,count])=>`${count} ${MEDIA_LABELS[kind]||kind}`).join(' · ')}
function topicMatches(section,query){if(!query)return true;const text=[section.label,section.description,section.editorialUse,...topicItems(archive,section.id).map(itemSearchText)].join(' ');return normalize(text).includes(normalize(query))}
function renderChooser(){const query=state.chooserQuery;const sections=allTopics(archive).filter(section=>topicMatches(section,query));const grid=q('[data-topic-grid]');grid.replaceChildren();sections.forEach((section,index)=>{const items=topicItems(archive,section.id);const button=document.createElement('button');button.type='button';button.className=`topic-card${section.kind==='editor-request'?' is-curated':''}`;button.dataset.topic=section.id;button.innerHTML='<span class="topic-number"></span><span class="topic-card-copy"><small class="topic-kind" hidden></small><strong></strong><span class="topic-description"></span><small class="topic-media"></small></span><span class="topic-card-count"></span><span class="topic-arrow" aria-hidden="true">←</span>';q('.topic-number',button).textContent=section.kind==='editor-request'?'★':String(index).padStart(2,'0');q('strong',button).textContent=section.label;const kind=q('.topic-kind',button);kind.hidden=section.kind!=='editor-request';kind.textContent='בקשה עריכתית מרוכזת';q('.topic-description',button).textContent=section.description;q('.topic-media',button).textContent=mediaSummary(items);q('.topic-card-count',button).textContent=`${items.length} פריטים`;button.addEventListener('click',()=>{state.lastTopicTrigger=button;routeTo(`#topic/${encodeURIComponent(section.id)}`)});grid.appendChild(button)});
 const allMatches=query?archive.items.filter(item=>normalize(itemSearchText(item)).includes(normalize(query))):[];const limited=allMatches.slice(0,8);const discovery=q('[data-search-discovery]');discovery.hidden=!query;q('[data-discovery-count]').textContent=query?`${allMatches.length} נמצאו${allMatches.length>limited.length?' · מוצגים 8':''}`:'';const list=q('[data-discovery-list]');list.replaceChildren();limited.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='discovery-item';button.innerHTML='<span><b></b><small></small></span><span aria-hidden="true">←</span>';q('b',button).textContent=item.title;q('small',button).textContent=`${item.sectionLabel} · ${item.id}`;button.addEventListener('click',()=>routeTo(`#item/${item.id}`));list.appendChild(button)});q('[data-chooser-summary]').textContent=query?`${sections.length} נושאים מתאימים`:`${allTopics(archive).length} נושאים · ${archive.items.length} פריטי ארכיון`;q('[data-clear-topic]').hidden=!query;
 if(!sections.length&&!limited.length){const empty=document.createElement('div');empty.className='state-panel';empty.innerHTML='<strong>לא נמצאו נושאים או פריטים</strong><span>נסו שם, תקופה או תיאור אחר.</span>';grid.appendChild(empty)}}
function mountOfficialPlayer(item,stage,button,{autoplay=true,focus=true}={}){const embed=trustedEmbedUrl(item.preview?.embedUrl);if(!embed)return;const finalUrl=new URL(embed);if(finalUrl.hostname==='www.youtube-nocookie.com'){finalUrl.searchParams.set('origin',location.origin);finalUrl.searchParams.set('widget_referrer',`${location.origin}${location.pathname}`);if(autoplay)finalUrl.searchParams.set('autoplay','1')}const iframe=document.createElement('iframe');iframe.src=finalUrl.href;iframe.title=`נגן רשמי: ${item.title}`;iframe.loading='lazy';iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allowFullscreen=true;stage.replaceChildren(iframe);stage.classList.add('is-playing');if(button)button.hidden=true;if(focus)iframe.focus();return iframe}
function buildMedia(item,card){const media=q('.asset-media',card);const preview=item.preview;const thumb=trustedMediaUrl(preview?.thumbnailUrl);if(preview?.embedUrl&&trustedEmbedUrl(preview.embedUrl)){mountOfficialPlayer(item,media,null,{autoplay:false,focus:false});return}
 if(preview?.kind?.endsWith('image')&&thumb){const figure=document.createElement('figure');const img=document.createElement('img');img.src=thumb;img.alt=preview.alt||item.title;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>{img.remove();figure.classList.add('is-broken')},{once:true});const caption=document.createElement('figcaption');caption.textContent=preview.caption||'תצוגה מקדימה מן המקור';figure.append(img,caption);media.appendChild(figure);return}
 const fallback=document.createElement('div');fallback.className='source-tile';fallback.innerHTML='<span></span><b>הקובץ עדיין לא נמצא בארכיון</b><small>אפשר לצפות במקור ולבקש קובץ מקורי מבעל הזכויות</small>';q('span',fallback).textContent=MEDIA_LABELS[item.mediaGroup]||item.mediaType;media.appendChild(fallback)}
function assetCard(item,topicId=''){const fragment=q('#asset-template').content.cloneNode(true);const card=q('.asset-card',fragment);card.id=item.id;card.dataset.itemId=item.id;card.tabIndex=-1;buildMedia(item,card);q('.asset-id',card).textContent=item.id;q('.asset-type',card).textContent=item.mediaType;const badge=q('.rights-badge',card);badge.textContent=rightsLabel(item);badge.classList.add(`is-${item.rightsGroup}`);const tags=topicRequestTags(archive,topicId,item.id),tagList=q('.request-tags',card);tagList.hidden=!tags.length;tags.forEach(tag=>{const chip=document.createElement('span');chip.className='request-tag';chip.textContent=`לאיתור: ${tag.label}`;chip.title=tag.note||'';tagList.appendChild(chip)});q('.asset-title',card).textContent=item.title;q('.asset-description',card).textContent=item.description||'תיאור חזותי טרם הושלם.';q('.editorial-note span',card).textContent=item.editorialUse||'נדרש מיון עריכתי נוסף.';q('.asset-source',card).textContent=item.source||'לא צוין';q('.asset-date',card).textContent=[item.date,item.period].filter(Boolean).join(' · ')||'לא צוין';q('.asset-owner',card).textContent=item.rightsOwner||'לא הוכרע';q('.asset-verification',card).textContent=item.verificationNote||'נדרשת צפייה ואימות לפני קאט.';q('.asset-next',card).textContent=item.nextAction||'לצפות ולאמת לפני שימוש';
 const source=q('.source-button',card);const sourceUrl=safeHttpUrl(item.sourceUrl);source.hidden=!sourceUrl;if(sourceUrl)source.href=sourceUrl;const download=trustedDownloadUrl(item),unavailable=q('.download-unavailable',card);if(download){const action=q('.download-button',card);action.hidden=false;action.href=download;action.download='';action.textContent=item.downloadLabel||'הורדת הקובץ';unavailable.hidden=true;source.classList.add('button-ghost')}else{source.textContent=item.mediaGroup==='stills'?'פתיחת התמונה במקור ↗':'פתיחת המקור ↗'}
 q('.copy-link',card).addEventListener('click',async()=>{const url=`${location.origin}${location.pathname}${location.search}#item/${item.id}`;try{await navigator.clipboard.writeText(url);toast('הקישור לפריט הועתק')}catch{history.replaceState(null,'',`#item/${item.id}`);toast('הפריט סומן בכתובת')}});return fragment}
function showTopic(topicId,{focus=false,openItem=''}={}){const section=allTopics(archive).find(entry=>entry.id===topicId);if(!section){home();return}state.view='topic';state.topicId=topicId;q('[data-chooser]').hidden=true;q('[data-topic-workspace]').hidden=false;q('[data-topic-title]').textContent=section.label;q('[data-breadcrumb-current]').textContent=section.label;q('[data-topic-description]').textContent=[section.description,section.editorialUse].filter(Boolean).join(' ');q('[data-topic-count]').textContent=topicItems(archive,topicId).length;renderTopicResults();if(focus)requestAnimationFrame(()=>q('[data-topic-title]').focus({preventScroll:true}));if(openItem)requestAnimationFrame(()=>{const card=document.getElementById(openItem);if(card){card.scrollIntoView({block:'center'});card.focus({preventScroll:true});q('.asset-details',card).open=true}})}
function renderTopicResults(){const all=topicItems(archive,state.topicId);const items=topicItems(archive,state.topicId,state.resultQuery);const results=q('[data-results]');results.replaceChildren();items.forEach(item=>results.appendChild(assetCard(item,state.topicId)));q('[data-result-count]').textContent=state.resultQuery?`${items.length} מתוך ${all.length} פריטים`:`כל ${all.length} הפריטים בנושא`;q('[data-empty]').hidden=items.length!==0;q('[data-clear-results]').hidden=!state.resultQuery}
function setup(meta){document.title=meta.title||document.title;q('[data-project-title]').textContent=meta.projectTitle||meta.subject||'מייקל לוין';setLink('[data-drive-root]',meta.driveRoot);setLink('[data-guide-pdf]',meta.guidePdf);q('[data-loading]').hidden=true;q('[data-topic-grid]').hidden=false;renderChooser();applyRoute()}
async function init(){q('[data-topic-grid]').hidden=true;q('[data-load-error]').hidden=true;try{const response=await fetch('data/archive.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.items)||!Array.isArray(data.meta?.sections))throw new Error('Invalid archive schema');archive=data;setup(archive.meta)}catch(error){q('[data-loading]').hidden=true;q('[data-load-error]').hidden=false;console.error(error)}}
let routeFrame=0;function scheduleRoute(){cancelAnimationFrame(routeFrame);routeFrame=requestAnimationFrame(()=>applyRoute({focus:true}))}
function bind(){q('#topic-search').addEventListener('input',event=>{state.chooserQuery=event.target.value;renderChooser()});q('[data-clear-topic]').addEventListener('click',()=>{state.chooserQuery='';q('#topic-search').value='';renderChooser();q('#topic-search').focus()});q('#result-search').addEventListener('input',event=>{state.resultQuery=event.target.value;renderTopicResults()});q('[data-clear-results]').addEventListener('click',clearResults);q('[data-reset-results]').addEventListener('click',clearResults);qa('[data-back-topics]').forEach(button=>button.addEventListener('click',()=>routeTo('')));q('[data-home-link]').addEventListener('click',event=>{event.preventDefault();routeTo('')});q('[data-retry]').addEventListener('click',init);window.addEventListener('popstate',scheduleRoute);window.addEventListener('hashchange',scheduleRoute)}
function clearResults(){state.resultQuery='';q('#result-search').value='';renderTopicResults();q('#result-search').focus()}
if(typeof document!=='undefined'){bind();init()}
