const DEFAULT_RIGHTS_LABELS={open:'פתוח בתנאים',permission:'נדרש אישור',commercial:'מסחרי',family:'משפחה',production:'הפקה',verify:'טעון בדיקה'};
const MEDIA_LABELS={video:'וידאו',stills:'סטילס',audio:'אודיו',web:'מקור קריאה'};
export const EMBED_HOSTS=new Set(['www.youtube-nocookie.com','www.facebook.com','archive.org']);
export const MEDIA_HOSTS=new Set(['i.ytimg.com','commons.wikimedia.org','upload.wikimedia.org','archive.org']);
const LOCAL_PREVIEW_PATH=/\/assets\/previews\/ML-\d{3}\.webp$/;
const DOWNLOAD_HOSTS=new Set(['upload.wikimedia.org']);

let archive=null;
const state={view:'topics',topicId:'',chooserQuery:'',resultQuery:'',pendingItemId:'',lastTopicTrigger:null};
const q=(selector,root=document)=>root.querySelector(selector);
const qa=(selector,root=document)=>[...root.querySelectorAll(selector)];
export const normalize=(value='')=>String(value).normalize('NFKD').replace(/[\u0591-\u05C7]/g,'').toLowerCase().replace(/[״׳'".,:;()\[\]{}\-–—_/\\]/g,' ').replace(/\s+/g,' ').trim();
export function itemSearchText(item){return [item.id,item.title,item.period,item.mediaType,item.description,item.editorialUse,item.subcategory,item.source,item.rightsOwner,item.rightsStatus].filter(Boolean).join(' ')}
export function topicItems(data,topicId,query=''){const needle=normalize(query);return data.items.filter(item=>item.section===topicId&&(!needle||normalize(itemSearchText(item)).includes(needle)))}
export function parseRoute(hash=''){let match=String(hash).match(/^#topic\/(.+)$/);if(match)return{kind:'topic',id:decodeURIComponent(match[1])};match=String(hash).match(/^#item\/(ML-\d{3})$/);if(match)return{kind:'item',id:match[1]};return{kind:'topics'}}
export function trustedDownloadUrl(item){if(item?.downloadAuthorized!==true||typeof item.downloadUrl!=='string')return'';try{const url=new URL(item.downloadUrl);return url.protocol==='https:'&&DOWNLOAD_HOSTS.has(url.hostname)&&url.pathname.startsWith('/wikipedia/commons/')?url.href:''}catch{return''}}
function safeHttpUrl(value){try{const url=new URL(value,location.href);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return''}}
function trustedEmbedUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&EMBED_HOSTS.has(url.hostname)?url.href:''}catch{return''}}
function trustedMediaUrl(value){try{const url=new URL(value,location.href);if(url.origin===location.origin&&LOCAL_PREVIEW_PATH.test(url.pathname))return url.href;return url.protocol==='https:'&&MEDIA_HOSTS.has(url.hostname)?url.href:''}catch{return''}}
function rightsLabel(item){return archive.meta.rightsLabels?.[item.rightsGroup]||DEFAULT_RIGHTS_LABELS[item.rightsGroup]||item.rightsStatus||'טעון בדיקה'}
function setLink(selector,url){qa(selector).forEach(link=>{const safe=url?safeHttpUrl(url):'';link.hidden=!safe;if(safe)link.href=safe})}
function toast(text){const el=q('[data-toast]');el.textContent=text;el.classList.add('is-visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('is-visible'),2200)}
function routeTo(hash,{replace=false}={}){const url=`${location.pathname}${location.search}${hash}`;(replace?history.replaceState:history.pushState).call(history,null,'',url);applyRoute({focus:true})}
function home({restoreFocus=false}={}){state.view='topics';state.topicId='';state.resultQuery='';state.pendingItemId='';q('[data-topic-workspace]').hidden=true;q('[data-chooser]').hidden=false;renderChooser();if(restoreFocus&&state.lastTopicTrigger?.isConnected)state.lastTopicTrigger.focus();else q('#topics-title').focus?.({preventScroll:true})}
function applyRoute({focus=false}={}){if(!archive)return;const route=parseRoute(location.hash);if(route.kind==='topic'&&archive.meta.sections.some(section=>section.id===route.id)){showTopic(route.id,{focus});return}if(route.kind==='item'){const item=archive.items.find(entry=>entry.id===route.id);if(item){state.pendingItemId=item.id;showTopic(item.section,{focus,openItem:item.id});return}}if(location.hash)history.replaceState(null,'',`${location.pathname}${location.search}`);home({restoreFocus:focus})}
function mediaSummary(items){const counts={video:0,stills:0,audio:0,web:0};items.forEach(item=>counts[item.mediaGroup]=(counts[item.mediaGroup]||0)+1);return Object.entries(counts).filter(([,count])=>count).map(([kind,count])=>`${count} ${MEDIA_LABELS[kind]||kind}`).join(' · ')}
function topicMatches(section,query){if(!query)return true;const text=[section.label,section.description,section.editorialUse,...archive.items.filter(item=>item.section===section.id).map(itemSearchText)].join(' ');return normalize(text).includes(normalize(query))}
function renderChooser(){const query=state.chooserQuery;const sections=archive.meta.sections.filter(section=>topicMatches(section,query));const grid=q('[data-topic-grid]');grid.replaceChildren();sections.forEach((section,index)=>{const items=archive.items.filter(item=>item.section===section.id);const button=document.createElement('button');button.type='button';button.className='topic-card';button.dataset.topic=section.id;button.innerHTML='<span class="topic-number"></span><span class="topic-card-copy"><strong></strong><span class="topic-description"></span><small class="topic-media"></small></span><span class="topic-card-count"></span><span class="topic-arrow" aria-hidden="true">←</span>';q('.topic-number',button).textContent=String(index+1).padStart(2,'0');q('strong',button).textContent=section.label;q('.topic-description',button).textContent=section.description;q('.topic-media',button).textContent=mediaSummary(items);q('.topic-card-count',button).textContent=`${items.length} פריטים`;button.addEventListener('click',()=>{state.lastTopicTrigger=button;routeTo(`#topic/${encodeURIComponent(section.id)}`)});grid.appendChild(button)});
 const allMatches=query?archive.items.filter(item=>normalize(itemSearchText(item)).includes(normalize(query))):[];const limited=allMatches.slice(0,8);const discovery=q('[data-search-discovery]');discovery.hidden=!query;q('[data-discovery-count]').textContent=query?`${allMatches.length} נמצאו${allMatches.length>limited.length?' · מוצגים 8':''}`:'';const list=q('[data-discovery-list]');list.replaceChildren();limited.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='discovery-item';button.innerHTML='<span><b></b><small></small></span><span aria-hidden="true">←</span>';q('b',button).textContent=item.title;q('small',button).textContent=`${item.sectionLabel} · ${item.id}`;button.addEventListener('click',()=>routeTo(`#item/${item.id}`));list.appendChild(button)});q('[data-chooser-summary]').textContent=query?`${sections.length} נושאים מתאימים`:`${archive.meta.sections.length} נושאים · ${archive.items.length} פריטי ארכיון`;q('[data-clear-topic]').hidden=!query;
 if(!sections.length&&!limited.length){const empty=document.createElement('div');empty.className='state-panel';empty.innerHTML='<strong>לא נמצאו נושאים או פריטים</strong><span>נסו שם, תקופה או תיאור אחר.</span>';grid.appendChild(empty)}}
function mountOfficialPlayer(item,stage,button){const embed=trustedEmbedUrl(item.preview?.embedUrl);if(!embed)return;const finalUrl=new URL(embed);if(finalUrl.hostname==='www.youtube-nocookie.com'){finalUrl.searchParams.set('origin',location.origin);finalUrl.searchParams.set('widget_referrer',`${location.origin}${location.pathname}`);finalUrl.searchParams.set('autoplay','1')}const iframe=document.createElement('iframe');iframe.src=finalUrl.href;iframe.title=`נגן רשמי: ${item.title}`;iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allowFullscreen=true;stage.replaceChildren(iframe);stage.classList.add('is-playing');button.hidden=true;iframe.focus()}
function buildMedia(item,card){const media=q('.asset-media',card);const preview=item.preview;const thumb=trustedMediaUrl(preview?.thumbnailUrl);if(preview?.embedUrl&&trustedEmbedUrl(preview.embedUrl)){const button=document.createElement('button');button.type='button';button.className='preview-play';button.setAttribute('aria-label',`ניגון בנגן הרשמי: ${item.title}`);if(thumb){const img=document.createElement('img');img.src=thumb;img.alt='';img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>img.remove(),{once:true});button.appendChild(img)}else{const placeholder=document.createElement('span');placeholder.className='preview-placeholder';placeholder.textContent=MEDIA_LABELS[item.mediaGroup]||'חומר ארכיון';button.appendChild(placeholder)}const play=document.createElement('span');play.className='play-mark';play.setAttribute('aria-hidden','true');play.textContent='▶';const label=document.createElement('span');label.className='play-label';label.textContent=preview.loadLabel||'ניגון באתר';button.append(play,label);button.addEventListener('click',()=>mountOfficialPlayer(item,media,button),{once:true});media.appendChild(button);return}
 if(preview?.kind==='open-image'&&thumb){const figure=document.createElement('figure');const img=document.createElement('img');img.src=thumb;img.alt=preview.alt||item.title;img.loading='lazy';img.decoding='async';const caption=document.createElement('figcaption');caption.textContent=preview.caption||'תצוגה מקדימה מן המקור';figure.append(img,caption);media.appendChild(figure);return}
 const fallback=document.createElement('div');fallback.className='source-tile';fallback.innerHTML='<span></span><b>תצוגה מקדימה אינה זמינה</b><small>החומר נשאר בקישור המקור</small>';q('span',fallback).textContent=MEDIA_LABELS[item.mediaGroup]||item.mediaType;media.appendChild(fallback)}
function assetCard(item){const fragment=q('#asset-template').content.cloneNode(true);const card=q('.asset-card',fragment);card.id=item.id;card.dataset.itemId=item.id;card.tabIndex=-1;buildMedia(item,card);q('.asset-id',card).textContent=item.id;q('.asset-type',card).textContent=item.mediaType;const badge=q('.rights-badge',card);badge.textContent=rightsLabel(item);badge.classList.add(`is-${item.rightsGroup}`);q('.asset-title',card).textContent=item.title;q('.asset-description',card).textContent=item.description||'תיאור חזותי טרם הושלם.';q('.editorial-note span',card).textContent=item.editorialUse||'נדרש מיון עריכתי נוסף.';q('.asset-source',card).textContent=item.source||'לא צוין';q('.asset-date',card).textContent=[item.date,item.period].filter(Boolean).join(' · ')||'לא צוין';q('.asset-owner',card).textContent=item.rightsOwner||'לא הוכרע';q('.asset-verification',card).textContent=item.verificationNote||'נדרשת צפייה ואימות לפני קאט.';q('.asset-next',card).textContent=item.nextAction||'לצפות ולאמת לפני שימוש';
 const source=q('.source-button',card),drive=q('.drive-button',card);const sourceUrl=safeHttpUrl(item.sourceUrl),driveUrl=safeHttpUrl(item.driveUrl||archive.meta.driveRoot);source.hidden=!sourceUrl;drive.hidden=!driveUrl;if(sourceUrl)source.href=sourceUrl;if(driveUrl)drive.href=driveUrl;const download=trustedDownloadUrl(item);if(download){const action=q('.download-button',card);action.hidden=false;action.href=download;action.download='';action.textContent=item.downloadLabel||`הורדת קובץ מקור · ${item.rightsStatus}`}
 q('.copy-link',card).addEventListener('click',async()=>{const url=`${location.origin}${location.pathname}${location.search}#item/${item.id}`;try{await navigator.clipboard.writeText(url);toast('הקישור לפריט הועתק')}catch{history.replaceState(null,'',`#item/${item.id}`);toast('הפריט סומן בכתובת')}});return fragment}
function showTopic(topicId,{focus=false,openItem=''}={}){const section=archive.meta.sections.find(entry=>entry.id===topicId);if(!section){home();return}state.view='topic';state.topicId=topicId;q('[data-chooser]').hidden=true;q('[data-topic-workspace]').hidden=false;q('[data-topic-title]').textContent=section.label;q('[data-breadcrumb-current]').textContent=section.label;q('[data-topic-description]').textContent=section.description;q('[data-topic-count]').textContent=archive.items.filter(item=>item.section===topicId).length;renderTopicResults();if(focus)requestAnimationFrame(()=>q('[data-topic-title]').focus({preventScroll:true}));if(openItem)requestAnimationFrame(()=>{const card=document.getElementById(openItem);if(card){card.scrollIntoView({block:'center'});card.focus({preventScroll:true});q('.asset-details',card).open=true}})}
function renderTopicResults(){const all=archive.items.filter(item=>item.section===state.topicId);const items=topicItems(archive,state.topicId,state.resultQuery);const results=q('[data-results]');results.replaceChildren();items.forEach(item=>results.appendChild(assetCard(item)));q('[data-result-count]').textContent=state.resultQuery?`${items.length} מתוך ${all.length} פריטים`:`כל ${all.length} הפריטים בנושא`;q('[data-empty]').hidden=items.length!==0;q('[data-clear-results]').hidden=!state.resultQuery}
function setup(meta){document.title=meta.title||document.title;q('[data-project-title]').textContent=meta.projectTitle||meta.subject||'מייקל לוין';setLink('[data-drive-root]',meta.driveRoot);setLink('[data-guide-pdf]',meta.guidePdf);q('[data-loading]').hidden=true;q('[data-topic-grid]').hidden=false;renderChooser();applyRoute()}
async function init(){q('[data-topic-grid]').hidden=true;q('[data-load-error]').hidden=true;try{const response=await fetch('data/archive.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.items)||!Array.isArray(data.meta?.sections))throw new Error('Invalid archive schema');archive=data;setup(archive.meta)}catch(error){q('[data-loading]').hidden=true;q('[data-load-error]').hidden=false;console.error(error)}}
let routeFrame=0;function scheduleRoute(){cancelAnimationFrame(routeFrame);routeFrame=requestAnimationFrame(()=>applyRoute({focus:true}))}
function bind(){q('#topic-search').addEventListener('input',event=>{state.chooserQuery=event.target.value;renderChooser()});q('[data-clear-topic]').addEventListener('click',()=>{state.chooserQuery='';q('#topic-search').value='';renderChooser();q('#topic-search').focus()});q('#result-search').addEventListener('input',event=>{state.resultQuery=event.target.value;renderTopicResults()});q('[data-clear-results]').addEventListener('click',clearResults);q('[data-reset-results]').addEventListener('click',clearResults);qa('[data-back-topics]').forEach(button=>button.addEventListener('click',()=>routeTo('')));q('[data-home-link]').addEventListener('click',event=>{event.preventDefault();routeTo('')});q('[data-retry]').addEventListener('click',init);window.addEventListener('popstate',scheduleRoute);window.addEventListener('hashchange',scheduleRoute)}
function clearResults(){state.resultQuery='';q('#result-search').value='';renderTopicResults();q('#result-search').focus()}
if(typeof document!=='undefined'){bind();init()}
