const DEFAULT_MEDIA_LABELS={all:'הכול',video:'וידאו וסרטים',stills:'צילום וסטילס',audio:'אודיו',web:'עמודים וכתבות'};
const DEFAULT_RIGHTS_LABELS={all:'כל הזכויות',open:'פתוח בתנאים',permission:'נדרש אישור',commercial:'מסחרי',family:'משפחה',production:'הפקה',verify:'טעון בדיקה'};
const RELEVANCE_LABELS={story:'סיפור',character:'דמות',evidence:'עדות',atmosphere:'אווירה',transition:'מעבר',context:'הקשר',motif:'מוטיב',archive:'ארכיון',technical:'טכני'};
const state={query:'',media:'all',rights:'all',section:'all'};
let archive=null;
const normalize=(s='')=>String(s).normalize('NFKD').replace(/[\u0591-\u05C7]/g,'').toLowerCase().replace(/[״׳'".,:;()\[\]{}\-–—_/\\]/g,' ').replace(/\s+/g,' ').trim();
const safeUrl=(value)=>{try{const u=new URL(value,location.href);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
const q=(sel,root=document)=>root.querySelector(sel);
const qa=(sel,root=document)=>[...root.querySelectorAll(sel)];
const setText=(sel,text)=>qa(sel).forEach(el=>{if(text!=null)el.textContent=text});
const setLink=(sel,url)=>qa(sel).forEach(a=>{if(url){a.href=safeUrl(url);a.hidden=false}else{a.hidden=true}});
function chip(label,value,group,count){const b=document.createElement('button');b.type='button';b.className='filter-chip';b.dataset[group]=value;b.textContent=count==null?label:`${label} · ${count}`;b.setAttribute('aria-pressed',String(state[group]===value));if(state[group]===value)b.classList.add('is-active');return b}
function setupPage(meta){
  document.title=meta.title||document.title;
  const desc=q('meta[name="description"]');if(desc&&meta.metaDescription)desc.content=meta.metaDescription;
  setText('[data-project-title]',meta.projectTitle||meta.subject||'מדריך חומרי גלם');
  setText('[data-project-subtitle]',meta.projectSubtitle||'מדריך לעורך');
  setText('[data-eyebrow]',meta.eyebrow||`תיק ארכיון הפקה · ${meta.catalogDate||''}`);
  setText('[data-hero-lede]',meta.heroLede||'שכבת התמצאות מעל מאגר החומרים: מה יש, מה רואים ולמה זה חשוב לסרט.');
  setText('[data-hero-rule]',meta.heroRule||'רואים · מבינים · ורק אז פותחים');
  setText('[data-hero-rule-note]',meta.heroRuleNote||'התיאור חוסך צפייה עיוורת; הוא אינו מחליף אימות לפני קאט.');
  setText('[data-total]',meta.total);setText('[data-section-count]',meta.sections.length);setText('[data-open-count]',meta.openLicensed??0);
  setText('[data-entry-count]',`כניסה ל־${meta.total} הפריטים`);setText('[data-start-title]',meta.startTitle||'דלתות הכניסה החזקות');setText('[data-start-intro]',meta.startIntro||'אם יש לעורך שעה אחת בלבד, מתחילים מכאן.');
  setText('[data-catalog-title]',meta.catalogTitle||'כל חומרי הגלם');setText('[data-footer-version]',`${meta.total} פריטים · גרסה ${meta.catalogDate||''}`);
  setText('[data-metric-total-label]',meta.metricTotalLabel||'פריטים מתוארים');setText('[data-metric-section-label]',meta.metricSectionLabel||'קטגוריות סיפור');setText('[data-metric-open-label]',meta.metricOpenLabel||'פריטים ברישיון פתוח');setText('[data-metric-route-value]',meta.metricRouteValue||'2');setText('[data-metric-route-label]',meta.metricRouteLabel||'נתיבים לכל פריט: מקור + אוסף');setText('[data-journey-title]',meta.journeyTitle||'ניווט לפי קטגוריה');
  setLink('[data-drive-root]',meta.driveRoot);setLink('[data-guide-pdf]',meta.guidePdf);setLink('[data-rights-map]',meta.rightsMap);
  if(meta.collectionLabel)qa('[data-drive-root]').forEach(a=>a.textContent=meta.collectionLabel);
  setText('[data-sidebar-eyebrow]',meta.sidebar?.eyebrow||'מפת זכויות');setText('[data-sidebar-title]',meta.sidebar?.title||'מה אפשר לעשות עכשיו?');
  const sidebar=q('[data-sidebar-steps]');sidebar.replaceChildren();(meta.sidebar?.steps||[
    {kind:'open',title:'פתוח בתנאים',description:'אפשר להשתמש רק עם הקרדיט ותנאי הרישיון.'},
    {kind:'permission',title:'נדרש אישור',description:'קישור למחקר בלבד; צריך master ורשות בכתב.'},
    {kind:'commercial',title:'ארכיון מסחרי',description:'יש לפנות לקבלת הצעת רישוי.'},
    {kind:'verify',title:'טעון בדיקה',description:'אין להכניס לעריכה לפני בירור מקור ובעלות.'}
  ]).forEach(x=>{const li=document.createElement('li');const dot=document.createElement('i');dot.className=`rights-dot is-${x.kind||'verify'}`;const span=document.createElement('span');const b=document.createElement('b');b.textContent=x.title;span.append(b,document.createTextNode(` ${x.description||''}`));li.append(dot,span);sidebar.appendChild(li)});
  const disclaimer=q('[data-footer-disclaimer]');if(meta.footerDisclaimer)disclaimer.textContent=meta.footerDisclaimer;
  const rightsMap=q('[data-rights-map]');if(meta.rightsMapLabel&&rightsMap)rightsMap.textContent=meta.rightsMapLabel;
  const leads=q('[data-start-leads]');leads.replaceChildren();(meta.startLeads||[]).forEach(x=>{const li=document.createElement('li');const b=document.createElement('b');b.textContent=x.title;const s=document.createElement('span');s.textContent=x.description;li.append(b,s);if(x.section){li.tabIndex=0;li.role='button';li.addEventListener('click',()=>selectSection(x.section))}leads.appendChild(li)});
}
function selectSection(id){state.section=id;render();q('#catalog').scrollIntoView()}
function buildJourney(meta){const nav=q('[data-section-nav]');nav.replaceChildren();meta.sections.forEach((s,i)=>{const b=document.createElement('button');b.type='button';b.className='journey-button';b.dataset.section=s.id;b.innerHTML=`<span class="journey-number">${String(i+1).padStart(2,'0')}</span><span class="journey-label"></span><span class="journey-count">${s.count} פריטים</span>`;q('.journey-label',b).textContent=s.label;b.addEventListener('click',()=>selectSection(s.id));nav.appendChild(b)})}
function buildFilters(meta){const media=q('[data-media-filters]');const rights=q('[data-rights-filters]');media.replaceChildren();rights.replaceChildren();const mediaLabels={...DEFAULT_MEDIA_LABELS,...(meta.mediaLabels||{})};const rightsLabels={...DEFAULT_RIGHTS_LABELS,...(meta.rightsLabels||{})};Object.entries(mediaLabels).filter(([v])=>v==='all'||(meta.mediaCounts[v]||0)>0).forEach(([v,l])=>media.appendChild(chip(l,v,'media',v==='all'?meta.total:meta.mediaCounts[v]||0)));Object.entries(rightsLabels).filter(([v])=>v==='all'||(meta.rightsCounts[v]||0)>0).forEach(([v,l])=>rights.appendChild(chip(l,v,'rights',v==='all'?meta.total:meta.rightsCounts[v]||0)));media.addEventListener('click',e=>{const b=e.target.closest('[data-media]');if(!b)return;state.media=b.dataset.media;render()});rights.addEventListener('click',e=>{const b=e.target.closest('[data-rights]');if(!b)return;state.rights=b.dataset.rights;render()})}
function searchable(item){return [item.id,item.title,item.period,item.mediaType,item.description,item.editorialUse,item.relevanceType,item.verificationNote,item.subcategory,item.source,item.rightsOwner,item.rightsStatus,item.nextAction,(item.timecodes||[]).map(x=>typeof x==='string'?x:`${x.at||''} ${x.label||''}`),(item.clipNames||[])].flat().join(' ')}
function matches(item){if(state.media!=='all'&&item.mediaGroup!==state.media)return false;if(state.rights!=='all'&&item.rightsGroup!==state.rights)return false;if(state.section!=='all'&&item.section!==state.section)return false;return !state.query||normalize(searchable(item)).includes(normalize(state.query))}
function rightsLabel(item){return archive.meta.rightsLabels?.[item.rightsGroup]||DEFAULT_RIGHTS_LABELS[item.rightsGroup]||item.rightsStatus}
function fillOptional(el,selector,value){const target=q(selector,el);const wrap=target?.closest('[data-optional]');if(value){target.textContent=value;if(wrap)wrap.hidden=false}else if(wrap)wrap.hidden=true}
const EMBED_HOSTS=new Set(['www.youtube-nocookie.com','www.facebook.com','archive.org']);
const MEDIA_HOSTS=new Set(['i.ytimg.com','commons.wikimedia.org','upload.wikimedia.org','archive.org']);
function trustedRemoteUrl(value,hosts){try{const u=new URL(value);return u.protocol==='https:'&&hosts.has(u.hostname)?u.href:''}catch{return ''}}
function trustedMediaUrl(value){try{const u=new URL(value,location.href);if(u.origin===location.origin&&/^\/assets\/previews\/ML-\d{3}\.webp$/.test(u.pathname))return u.href;return u.protocol==='https:'&&MEDIA_HOSTS.has(u.hostname)?u.href:''}catch{return ''}}
function mountPreview(item,el){
  const p=item.preview;if(!p)return;el.classList.add('has-preview');
  const figure=q('.item-preview-summary',el),thumb=q('.item-preview-image',el),placeholder=q('.item-preview-placeholder',el),badge=q('.item-preview-badge',el),caption=q('.item-preview-caption',el);
  figure.hidden=false;caption.textContent=p.caption||'תצוגה מקדימה מן המקור';badge.hidden=!p.embedUrl;
  const thumbUrl=trustedMediaUrl(p.thumbnailUrl);
  if(thumbUrl){thumb.src=thumbUrl;thumb.alt=p.alt||`תצוגה מקדימה: ${item.title}`;thumb.hidden=false;placeholder.hidden=true;thumb.addEventListener('error',()=>{thumb.hidden=true;placeholder.hidden=false},{once:true})}
  else{thumb.hidden=true;placeholder.hidden=false;q('span',placeholder).textContent=p.kind==='facebook'?'Facebook':'חומר ארכיון'}
  const viewer=q('.item-viewer',el),stage=q('.item-viewer-stage',el),load=q('.item-load-player',el),note=q('.item-viewer-note',el);viewer.hidden=false;note.textContent=p.kind==='open-image'?'מוצג עותק preview מקומי של קובץ Wikimedia Commons ברישיון פתוח. יש לשמור את הקרדיט ותנאי הרישיון.':'הנגן מגיע מפלטפורמת המקור. צפייה כאן אינה אישור לשילוב החומר בסרט.';
  if(p.kind==='open-image'&&thumbUrl){const img=document.createElement('img');img.src=thumbUrl;img.alt=p.alt||item.title;img.loading='lazy';stage.appendChild(img)}
  else if(p.embedUrl){const embedUrl=trustedRemoteUrl(p.embedUrl,EMBED_HOSTS);if(embedUrl){load.hidden=false;load.textContent=p.loadLabel||'צפייה באתר';load.addEventListener('click',()=>{const finalUrl=new URL(embedUrl);if(finalUrl.hostname==='www.youtube-nocookie.com'){finalUrl.searchParams.set('origin',location.origin);finalUrl.searchParams.set('widget_referrer',`${location.origin}${location.pathname}`)}const iframe=document.createElement('iframe');iframe.src=finalUrl.href;iframe.title=`נגן: ${item.title}`;iframe.loading='lazy';iframe.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allowFullscreen=true;stage.replaceChildren(iframe);load.hidden=true},{once:true})}}
}
function itemNode(item){const frag=q('#item-template').content.cloneNode(true);const el=q('.archive-item',frag);el.id=item.id;q('.item-index',el).textContent=item.id;q('.item-period',el).textContent=item.period||item.sectionLabel;q('.item-media',el).textContent=item.mediaType;const rp=q('.rights-pill',el);rp.textContent=rightsLabel(item);rp.classList.add(`is-${item.rightsGroup}`);q('.item-title',el).textContent=item.title;q('.item-description',el).textContent=item.description||'תיאור חזותי טרם הושלם.';q('.item-editorial-use-text',el).textContent=item.editorialUse||'נדרש מיון עריכתי נוסף.';const rel=q('.relevance-pill',el);rel.textContent=RELEVANCE_LABELS[item.relevanceType]||item.relevanceType||'הקשר';q('.item-verification',el).textContent=item.verificationNote||'מבוסס מטא־דאטה; נדרשת צפייה לפני קאט.';fillOptional(el,'.item-subcategory',item.subcategory);q('.item-source',el).textContent=item.source||'לא צוין';q('.item-owner',el).textContent=item.rightsOwner||'לא הוכרע';q('.item-date',el).textContent=item.date||'לא צוין';q('.item-next',el).textContent=item.nextAction||'לצפות ולאמת לפני שימוש';mountPreview(item,el);
  const tcWrap=q('.item-timecodes-wrap',el),tc=q('.item-timecodes',el);(item.timecodes||[]).forEach(x=>{const li=document.createElement('li');li.textContent=typeof x==='string'?x:`${x.at||''}${x.label?` — ${x.label}`:''}`;tc.appendChild(li)});tcWrap.hidden=!item.timecodes?.length;
  const clipsWrap=q('.item-clips-wrap',el),clips=q('.item-clips',el);(item.clipNames||[]).forEach(x=>{const li=document.createElement('li');li.textContent=x;clips.appendChild(li)});clipsWrap.hidden=!item.clipNames?.length;
  const source=q('.source-button',el),drive=q('.drive-button',el);source.href=safeUrl(item.sourceUrl);drive.href=safeUrl(item.driveUrl||archive.meta.driveRoot);source.hidden=!item.sourceUrl;drive.hidden=!(item.driveUrl||archive.meta.driveRoot);if(archive.meta.itemCollectionLabel&&drive)drive.textContent=archive.meta.itemCollectionLabel;
  q('.copy-link',el).addEventListener('click',async()=>{const url=new URL(location.href);url.hash=item.id;try{await navigator.clipboard.writeText(url.href);toast('הקישור לפריט הועתק')}catch{location.hash=item.id;toast('הפריט סומן בכתובת')}});el.addEventListener('toggle',()=>{if(el.open)history.replaceState(null,'',`#${item.id}`)});return frag}
function render(){const filtered=archive.items.filter(matches);const results=q('[data-results]');results.replaceChildren();archive.meta.sections.forEach(section=>{const items=filtered.filter(i=>i.section===section.id);if(!items.length)return;const block=document.createElement('section');block.className='result-section';block.id=`section-${section.id}`;const head=document.createElement('div');head.className='result-section-head';const copy=document.createElement('div');const h=document.createElement('h2');h.textContent=section.label;copy.appendChild(h);if(section.description){const p=document.createElement('p');p.className='section-description';p.textContent=section.description;copy.appendChild(p)}if(section.editorialUse){const p=document.createElement('p');p.className='section-editorial-use';p.innerHTML='<b>למה הקטגוריה חשובה:</b> ';p.append(document.createTextNode(section.editorialUse));copy.appendChild(p)}const c=document.createElement('span');c.textContent=`${items.length} פריטים`;head.append(copy,c);const list=document.createElement('div');list.className='result-list';items.forEach(i=>list.appendChild(itemNode(i)));block.append(head,list);results.appendChild(block)});q('[data-result-count]').textContent=`${filtered.length} מתוך ${archive.meta.total} פריטים`;q('[data-empty]').hidden=filtered.length!==0;q('[data-clear-filters]').hidden=state.query===''&&state.media==='all'&&state.rights==='all'&&state.section==='all';qa('[data-media]').forEach(b=>{const on=b.dataset.media===state.media;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',String(on))});qa('[data-rights]').forEach(b=>{const on=b.dataset.rights===state.rights;b.classList.toggle('is-active',on);b.setAttribute('aria-pressed',String(on))});qa('[data-section]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.section===state.section)));openHashItem()}
function openHashItem(){const id=decodeURIComponent(location.hash.slice(1));if(!id||!/^[A-Za-z0-9_-]{2,40}$/.test(id))return;const el=document.getElementById(id);if(el){el.open=true;requestAnimationFrame(()=>el.scrollIntoView({block:'center'}))}}
let toastTimer;function toast(text){const el=q('[data-toast]');el.textContent=text;el.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('is-visible'),2200)}
async function init(){try{const response=await fetch('data/archive.json',{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);archive=await response.json();setupPage(archive.meta);buildJourney(archive.meta);buildFilters(archive.meta);const search=q('#archive-search');search.addEventListener('input',()=>{state.query=search.value;render()});search.addEventListener('keydown',e=>{if(e.key==='Escape'){search.value='';state.query='';render()}});q('[data-clear-filters]').addEventListener('click',()=>{state.query='';state.media='all';state.rights='all';state.section='all';search.value='';render()});window.addEventListener('hashchange',openHashItem);render()}catch(error){q('[data-results]').innerHTML='<div class="empty-state"><strong>הקטלוג לא נטען</strong><span>אפשר לפתוח בינתיים את מאגר החומרים מהכפתור העליון.</span></div>';console.error(error)}}
init();
